FROM golang:1.16.3-alpine3.13 as builder
WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
COPY ./src /go/src/
RUN go build -o /go/build/hello main

FROM scratch
COPY --from=builder /go/build/hello /
CMD ["/hello"]
